# Preload the wallpaper so hyprpaper loads it into memory
preload = ~/.config/backgrounds/develop-ship.jpg

# Set wallpaper on your monitor
wallpaper {
    monitor = eDP-1
    path = ~/.config/backgrounds/develop-ship.jpg
    fit_mode = cover
}

