# Preload the wallpaper so hyprpaper loads it into memory
preload = ~/.config/backgrounds/kratos_01.png

# Set wallpaper on your monitor
wallpaper {
    monitor = eDP-1
    path = ~/.config/backgrounds/kratos_01.png
    fit_mode = cover
}

